#pragma once

#define SCYLLA_HIDE_MAJOR_VERSION 0
#define SCYLLA_HIDE_MINOR_VERSION 6

#define STR(x) #x
#define STRW(x) L#x
#define SCYLLA_HIDE_VERSION_STRING_A STR(SCYLLA_HIDE_MAJOR_VERSION) "." STR(SCYLLA_HIDE_MINOR_VERSION)
#define SCYLLA_HIDE_VERSION_STRING_W STRW(SCYLLA_HIDE_MAJOR_VERSION) L"." STRW(SCYLLA_HIDE_MINOR_VERSION)

