#pragma once

#define SCYLLA_HIDE_MAJOR_VERSION 1
#define SCYLLA_HIDE_MINOR_VERSION 2

#define STRA(x) #x
#define STRW(x) L#x

#define STR_HELPERA(x) STRA(x)
#define STR_HELPERW(x) STRW(x)

#define SCYLLA_HIDE_VERSION_STRING_A STR_HELPERA(SCYLLA_HIDE_MAJOR_VERSION) "." STR_HELPERA(SCYLLA_HIDE_MINOR_VERSION)
#define SCYLLA_HIDE_VERSION_STRING_W STR_HELPERW(SCYLLA_HIDE_MAJOR_VERSION) L"." STR_HELPERW(SCYLLA_HIDE_MINOR_VERSION)


